table ROC
	lineageTag: 4064feb1-4224-4433-82a4-b806ff6609b9

	column FPR
		dataType: double
		formatString: 0%
		lineageTag: 40b0e17f-ff70-495d-a536-4efeb46b4b59
		summarizeBy: none
		sourceColumn: FPR

	column TPR
		dataType: double
		formatString: 0%
		lineageTag: 9d7af173-f7d2-44c8-9a17-f16f1d7c93f9
		summarizeBy: none
		sourceColumn: TPR

	partition ROC = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\ROC.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Clean = Table.ReplaceValue(Headers, "", null, Replacer.ReplaceValue, Table.ColumnNames(Headers)),
				    Typed = Table.TransformColumnTypes(Clean, {{"FPR", type number}, {"TPR", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

